name: Linting
on:
  push:

jobs:
  prettier:
    name: Checks formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: npx prettier ./index.html --check
